name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set-up OCaml
      run: sudy apt-get install -y ocaml ocaml-dune
    - name: Build
      run: make
    - name: Test
      run: make test
