name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup OCaml
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: 5.1
    - name: Pin locally
      run: opam pin -y add -n .
    - name: Install locally
      run: opam install -y -t levenfind
    - name: Test
      run: opam exec dune test
