name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Switch to latest Ubuntu
      run: |
        sudo sed -i 's/noble/questing/' /etc/apt/sources.list
        sudo apt-get -y update
    - name: Install packages
      run: sudo apt-get -y install ocaml ocaml-dune
    - name: Build
      run: dune build
    - name: Test
      run: dune test
